name: Deploy

on: pull_request

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Deploy Files
      run: |
        git config user.name samuel-rodrigues
        git config user.email "carlossamuel.rodrigues@gmail.com"
