name: Deploy

on: pull_request

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Deploy Files
      run: |
        git config user.name ${{ secrets.GH_USER }}
        git config user.email "${{ secrets.GH_EMAIL }}"
